Model Class Reference
Class responsible for executing the simulation.
#include <Model.h>
Public Member Functions
Model ()
Default constructor.
virtual ~Model ()
Virtual destructor.
Model (const Model &other)
Copy constructor.
Model & operator= (const Model &other)
Assignment operator.
void add (System *system)
Adds a system to the model.
void add (Flow *flow)
Adds a flow to the model.
void run (int begin, int end)
Executes the simulation in the specified time interval.
Private Attributes
vector< System * > systems
Vector of pointers to systems in the model.
vector< Flow * > flows
Vector of pointers to flows in the model.
Detailed Description
Class responsible for executing the simulation.
The model contains and manages a set of systems and flows. It is responsible for storing them and executing the temporal evolution of the simulation, applying the transfer rules between systems in each iteration.
Definition at line 32 of file Model.h.
Constructor & Destructor Documentation
Model() [1/2]
Model::Model () [default]
Default constructor.
Implementation of the default constructor.
Initializes an empty model.
Referenced by Model(), operator=(), and ~Model().
~Model()
Model::~Model () [virtual], [default]
Virtual destructor.
References Model().
Model() [2/2]
Model::Model (const Model & other)
Copy constructor.
Implementation of the copy constructor.
Parameters
other Model object to be copied.
Copies the systems and flows vectors from the original model.
Definition at line 27 of file Model.cpp.
    : systems(other.systems), flows(other.flows) {}
References flows, Model(), and systems.
Member Function Documentation
add() [1/2]
void Model::add (Flow * flow)
Adds a flow to the model.
Parameters
flow Pointer to the flow to be added.
Inserts the flow pointer into the flows vector.
Definition at line 55 of file Model.cpp.
                          {
    flows.push_back(flow);
}
References flows.
add() [2/2]
void Model::add (System * system)
Adds a system to the model.
Parameters
system Pointer to the system to be added.
Inserts the system pointer into the systems vector.
Definition at line 46 of file Model.cpp.
                              {
    systems.push_back(system);
}
References systems.
Referenced by complexFuncionalTest(), exponentialFuncionalTest(), and logisticalFuncionalTest().
operator=()
Model & Model::operator= (const Model & other)
Assignment operator.
Implementation of the assignment operator.
Parameters
other Model object to be assigned.
Returns
Reference to the modified Model object.
Definition at line 33 of file Model.cpp.
                                        {
    if (this != &other) {
        systems = other.systems;
        flows = other.flows;
    }
    return *this;
}
References flows, Model(), and systems.
run()
void Model::run (int begin, int end)
Executes the simulation in the specified time interval.
Simulates the evolution of the system from the initial time to the final time, applying flows in each iteration and updating system values.
Parameters
begin Initial simulation time (inclusive).
end Final simulation time (exclusive).
For each time unit in the interval [begin, end):
Calculates the value transferred by each flow
Reduces the value of the source system
Increases the value of the sink system
For each time unit in the interval [begin, end):
Executes each flow and stores its return value
For each flow:
Deducts the value from the source system (if not null)
Adds the value to the sink system (if not null)
Definition at line 69 of file Model.cpp.
                                  {
    for (int time = begin; time < end; time++) {
        vector<double> values;
        for (auto flow : flows) {
            values.push_back(flow->execute());
        }
        for (size_t i = 0; i < flows.size(); i++) {
            Flow* flow = flows[i];
            System* source = flow->getSource();
            System* sink = flow->getSink();
            double value = values[i];
            if (source != nullptr) {
                source->setValue(source->getValue() - value);
            }
            if (sink != nullptr) {
                sink->setValue(sink->getValue() + value);
            }
        }
    }
}
References flows, Flow::getSink(), Flow::getSource(), System::getValue(), and System::setValue().
Referenced by complexFuncionalTest(), exponentialFuncionalTest(), and logisticalFuncionalTest().
Member Data Documentation
flows
vector<Flow*> Model::flows [private]
Vector of pointers to flows in the model.
Definition at line 35 of file Model.h.
Referenced by add(), Model(), operator=(), and run().
systems
vector<System*> Model::systems [private]
Vector of pointers to systems in the model.
Definition at line 34 of file Model.h.
Referenced by add(), Model(), and operator=().
The documentation for this class was generated from the following files:
Model.h
Model.cpp