System Class Reference
Represents a system with variable state in the simulation.
#include <System.h>
Public Member Functions
System ()
Default constructor of the System class.
System (const string &name, double value)
Constructor with parameters.
virtual ~System ()
Virtual destructor.
System (const System &other)
Copy constructor.
System & operator= (const System &other)
Assignment operator.
void setName (const string &name)
Sets the name of the system.
void setValue (double value)
Sets the value of the system state.
string getName () const
Gets the name of the system.
double getValue () const
Gets the current value of the system.
Private Attributes
string name
Identifier name of the system.
double value
Current value of the system state.
Detailed Description
Represents a system with variable state in the simulation.
A system has an identifier name and a value that represents its current state. Systems can be connected through flows to transfer values between them during simulation execution.
Definition at line 27 of file System.h.
Constructor & Destructor Documentation
System() [1/3]
System::System ()
Default constructor of the System class.
Implementation of the default constructor.
Initializes the system with empty name and zero value.
Initializes the name as empty string and value as 0.0.
Definition at line 17 of file System.cpp.
: name(""), value(0.0) {}
References name, and value.
Referenced by operator=(), System(), and ~System().
System() [2/3]
System::System (const string & name, double value)
Constructor with parameters.
Implementation of the constructor with parameters.
Parameters
name Identifier name of the system.
value Initial value of the system state.
Initializes the system with the provided name and value.
Definition at line 24 of file System.cpp.
    : name(name), value(value) {}
References name, and value.
~System()
System::~System () [virtual], [default]
Virtual destructor.
References name, System(), and value.
System() [3/3]
System::System (const System & other)
Copy constructor.
Implementation of the copy constructor.
Parameters
other System object to be copied.
Copies the name and state values from the original object.
Definition at line 37 of file System.cpp.
    : name(other.name), value(other.value) {}
References name, System(), and value.
Member Function Documentation
getName()
string System::getName () const
Gets the name of the system.
Returns the name of the system.
Returns
Name of the system.
Definition at line 70 of file System.cpp.
                             {
    return name;
}
References name.
getValue()
double System::getValue () const
Gets the current value of the system.
Returns the current value of the system.
Returns
Current value of the state.
Definition at line 77 of file System.cpp.
                              {
    return value;
}
References value.
Referenced by complexFuncionalTest(), exponentialFuncionalTest(), logisticalFuncionalTest(), and Model::run().
operator=()
System & System::operator= (const System & other)
Assignment operator.
Implementation of the assignment operator.
Parameters
other System object to be assigned.
Returns
Reference to the modified System object.
Checks self-assignment before copying the values.
Definition at line 45 of file System.cpp.
                                           {
    if (this != &other) {
        name = other.name;
        value = other.value;
    }
    return *this;
}
References name, System(), and value.
setName()
void System::setName (const string & name)
Sets the name of the system.
Parameters
name New name of the system.
Definition at line 56 of file System.cpp.
                                       {
    this->name = name;
}
References name.
setValue()
void System::setValue (double value)
Sets the value of the system state.
Parameters
value New value of the state.
Definition at line 63 of file System.cpp.
                                  {
    this->value = value;
}
References value.
Referenced by Model::run().
Member Data Documentation
name
string System::name [private]
Identifier name of the system.
Definition at line 29 of file System.h.
Referenced by getName(), operator=(), setName(), System(), System(), System(), and ~System().
value
double System::value [private]
Current value of the system state.
Definition at line 30 of file System.h.
Referenced by getValue(), operator=(), setValue(), System(), System(), System(), and ~System().
The documentation for this class was generated from the following files:
System.h
System.cpp