LogisticFlow Class Reference
Implements a logistic flow with population limit.
#include <LogisticFlow.h>
Public Member Functions
LogisticFlow ()
Default constructor.
LogisticFlow (System *source, System *sink, double pmax)
Constructor with parameters.
virtual ~LogisticFlow ()
Virtual destructor.
LogisticFlow (const LogisticFlow &other)
Copy constructor.
LogisticFlow & operator= (const LogisticFlow &other)
Assignment operator.
double execute () override
Calculates and returns the logistic flow.
Public Member Functions inherited from Flow
Flow ()
Default constructor.
Flow (System *source, System *sink)
Constructor with parameters.
virtual ~Flow ()
Virtual destructor.
Flow (const Flow &other)
Copy constructor.
Flow & operator= (const Flow &other)
Assignment operator.
System * getSource () const
Gets the source system of the flow.
System * getSink () const
Gets the sink system of the flow.
Private Attributes
double pmax
Maximum population that limits growth.
Additional Inherited Members
Protected Attributes inherited from Flow
System * source
Pointer to the source system of the flow.
System * sink
Pointer to the sink system of the flow.
Detailed Description
Implements a logistic flow with population limit.
The LogisticFlow calculates the value transferred through a logistic function that simulates growth limited by environmental capacity.
The formula used is: flow = 0.3 * P * (1 - P/pmax) where P is the current value of the sink system and pmax is the maximum population.
Definition at line 27 of file LogisticFlow.h.
Constructor & Destructor Documentation
LogisticFlow() [1/3]
LogisticFlow::LogisticFlow ()
Default constructor.
Implementation of the default constructor.
Definition at line 15 of file LogisticFlow.cpp.
: Flow(), pmax(0.0) {}
References Flow::Flow(), and pmax.
Referenced by LogisticFlow(), operator=(), and ~LogisticFlow().
LogisticFlow() [2/3]
LogisticFlow::LogisticFlow (System * source, System * sink, double pmax)
Constructor with parameters.
Implementation of the constructor with parameters.
Parameters
source Pointer to the source system.
sink Pointer to the sink system.
pmax Maximum population value to limit growth.
Definition at line 20 of file LogisticFlow.cpp.
    : Flow(source, sink), pmax(pmax) {}
References Flow::Flow(), pmax, Flow::sink, and Flow::source.
~LogisticFlow()
LogisticFlow::~LogisticFlow () [virtual], [default]
Virtual destructor.
References LogisticFlow().
LogisticFlow() [3/3]
LogisticFlow::LogisticFlow (const LogisticFlow & other)
Copy constructor.
Implementation of the copy constructor.
Parameters
other LogisticFlow object to be copied.
Definition at line 31 of file LogisticFlow.cpp.
    : Flow(other), pmax(other.pmax) {}
References Flow::Flow(), LogisticFlow(), and pmax.
Member Function Documentation
execute()
double LogisticFlow::execute () [override], [virtual]
Calculates and returns the logistic flow.
Implementation of the execute() method.
Returns
Flow value calculated by the logistic function.
Implements the formula: 0.3 * P * (1 - P/pmax) If the sink system is null, returns 0.
Calculates the logistic flow as: 0.3 * P * (1 - P/pmax) where P is the value of the sink system and pmax is the maximum population.
Returns
Transfer value calculated by the logistic formula.
Implements Flow.
Definition at line 53 of file LogisticFlow.cpp.
                             {
    if (sink != nullptr) {
        double P = sink->getValue();
        return 0.3 * P * (1 - P / pmax);
    }
    return 0;
}
References pmax, and Flow::sink.
operator=()
LogisticFlow & LogisticFlow::operator= (const LogisticFlow & other)
Assignment operator.
Implementation of the assignment operator.
Parameters
other LogisticFlow object to be assigned.
Returns
Reference to the modified LogisticFlow object.
Definition at line 37 of file LogisticFlow.cpp.
                                                             {
    if (this != &other) {
        Flow::operator=(other);
        pmax = other.pmax;
    }
    return *this;
}
References LogisticFlow(), Flow::operator=(), and pmax.
Member Data Documentation
pmax
double LogisticFlow::pmax [private]
Maximum population that limits growth.
Definition at line 29 of file LogisticFlow.h.
Referenced by execute(), LogisticFlow(), LogisticFlow(), LogisticFlow(), and operator=().
The documentation for this class was generated from the following files:
LogisticFlow.h
LogisticFlow.cpp