ExponentialFlow Class Reference
Implements a flow with exponential growth.
#include <ExponentialFlow.h>
Public Member Functions
ExponentialFlow ()
Default constructor.
ExponentialFlow (System *source, System *sink)
Constructor with parameters.
virtual ~ExponentialFlow ()
Virtual destructor.
ExponentialFlow (const ExponentialFlow &other)
Copy constructor.
ExponentialFlow & operator= (const ExponentialFlow &other)
Assignment operator.
double execute () override
Calculates and returns the exponential flow.
Public Member Functions inherited from Flow
Flow ()
Default constructor.
Flow (System *source, System *sink)
Constructor with parameters.
virtual ~Flow ()
Virtual destructor.
Flow (const Flow &other)
Copy constructor.
Flow & operator= (const Flow &other)
Assignment operator.
System * getSource () const
Gets the source system of the flow.
System * getSink () const
Gets the sink system of the flow.
Additional Inherited Members
Protected Attributes inherited from Flow
System * source
Pointer to the source system of the flow.
System * sink
Pointer to the sink system of the flow.
Detailed Description
Implements a flow with exponential growth.
The ExponentialFlow calculates the value transferred through an exponential growth equation, where the transfer rate is proportional to the current value of the sink system.
The formula used is: flow = 0.3 * sink_value
Definition at line 27 of file ExponentialFlow.h.
Constructor & Destructor Documentation
ExponentialFlow() [1/3]
ExponentialFlow::ExponentialFlow ()
Default constructor.
Implementation of the default constructor.
Definition at line 15 of file ExponentialFlow.cpp.
: Flow() {}
References Flow::Flow().
Referenced by ExponentialFlow(), operator=(), and ~ExponentialFlow().
ExponentialFlow() [2/3]
ExponentialFlow::ExponentialFlow (System * source, System * sink)
Constructor with parameters.
Implementation of the constructor with parameters.
Parameters
source Pointer to the source system.
sink Pointer to the sink system.
Definition at line 20 of file ExponentialFlow.cpp.
    : Flow(source, sink) {}
References Flow::Flow(), Flow::sink, and Flow::source.
~ExponentialFlow()
ExponentialFlow::~ExponentialFlow () [virtual], [default]
Virtual destructor.
References ExponentialFlow().
ExponentialFlow() [3/3]
ExponentialFlow::ExponentialFlow (const ExponentialFlow & other)
Copy constructor.
Implementation of the copy constructor.
Parameters
other ExponentialFlow object to be copied.
Definition at line 31 of file ExponentialFlow.cpp.
    : Flow(other) {}
References ExponentialFlow(), and Flow::Flow().
Member Function Documentation
execute()
double ExponentialFlow::execute () [override], [virtual]
Calculates and returns the exponential flow.
Implementation of the execute() method.
Returns
Flow value calculated as 0.3 * sink_value.
If the sink system is null, returns 0.
Calculates the exponential flow as: 0.3 * sink_value
Returns
Transfer value calculated by the exponential formula.
Implements Flow.
Definition at line 51 of file ExponentialFlow.cpp.
                                {
    if (sink != nullptr) {
        return 0.3 * sink->getValue();
    }
    return 0;
}
References Flow::sink.
operator=()
ExponentialFlow & ExponentialFlow::operator= (const ExponentialFlow & other)
Assignment operator.
Implementation of the assignment operator.
Parameters
other ExponentialFlow object to be assigned.
Returns
Reference to the modified ExponentialFlow object.
Definition at line 37 of file ExponentialFlow.cpp.
                                                                      {
    if (this != &other) {
        Flow::operator=(other);
    }
    return *this;
}
References ExponentialFlow(), and Flow::operator=().
The documentation for this class was generated from the following files:
ExponentialFlow.h
ExponentialFlow.cpp