ComplexFlow Class Reference
Implements a flow with specific calculation rule.
#include <ComplexFlow.h>
Public Member Functions
ComplexFlow ()
Default constructor.
ComplexFlow (System *source, System *sink)
Constructor with parameters.
virtual ~ComplexFlow ()
Virtual destructor.
ComplexFlow (const ComplexFlow &other)
Copy constructor.
ComplexFlow & operator= (const ComplexFlow &other)
Assignment operator.
double execute () override
Calculates and returns the complex flow.
Public Member Functions inherited from Flow
Flow ()
Default constructor.
Flow (System *source, System *sink)
Constructor with parameters.
virtual ~Flow ()
Virtual destructor.
Flow (const Flow &other)
Copy constructor.
Flow & operator= (const Flow &other)
Assignment operator.
System * getSource () const
Gets the source system of the flow.
System * getSink () const
Gets the sink system of the flow.
Additional Inherited Members
Protected Attributes inherited from Flow
System * source
Pointer to the source system of the flow.
System * sink
Pointer to the sink system of the flow.
Detailed Description
Implements a flow with specific calculation rule.
The ComplexFlow calculates the value transferred based on a specific rule that depends on the value of the source system.
The formula used is: flow = 0.01 * source_value
Definition at line 25 of file ComplexFlow.h.
Constructor & Destructor Documentation
ComplexFlow() [1/3]
ComplexFlow::ComplexFlow ()
Default constructor.
Implementation of the default constructor.
Definition at line 15 of file ComplexFlow.cpp.
: Flow() {}
References Flow::Flow().
Referenced by ComplexFlow(), operator=(), and ~ComplexFlow().
ComplexFlow() [2/3]
ComplexFlow::ComplexFlow (System * source, System * sink)
Constructor with parameters.
Implementation of the constructor with parameters.
Parameters
source Pointer to the source system.
sink Pointer to the sink system.
Definition at line 20 of file ComplexFlow.cpp.
    : Flow(source, sink) {}
References Flow::Flow(), Flow::sink, and Flow::source.
~ComplexFlow()
ComplexFlow::~ComplexFlow () [virtual], [default]
Virtual destructor.
References ComplexFlow().
ComplexFlow() [3/3]
ComplexFlow::ComplexFlow (const ComplexFlow & other)
Copy constructor.
Implementation of the copy constructor.
Parameters
other ComplexFlow object to be copied.
Definition at line 31 of file ComplexFlow.cpp.
    : Flow(other) {}
References ComplexFlow(), and Flow::Flow().
Member Function Documentation
execute()
double ComplexFlow::execute () [override], [virtual]
Calculates and returns the complex flow.
Implementation of the execute() method.
Returns
Flow value calculated as 0.01 * source_value.
The transfer is based on the value of the source system.
Calculates the complex flow as: 0.01 * source_value
Returns
Transfer value calculated by the complex formula.
Implements Flow.
Definition at line 51 of file ComplexFlow.cpp.
                            {
    return 0.01 * source->getValue();
}
References Flow::source.
operator=()
ComplexFlow & ComplexFlow::operator= (const ComplexFlow & other)
Assignment operator.
Implementation of the assignment operator.
Parameters
other ComplexFlow object to be assigned.
Returns
Reference to the modified ComplexFlow object.
Definition at line 37 of file ComplexFlow.cpp.
                                                          {
    if (this != &other) {
        Flow::operator=(other);
    }
    return *this;
}
References ComplexFlow(), and Flow::operator=().
The documentation for this class was generated from the following files:
ComplexFlow.h
ComplexFlow.cpp