funcional_tests.cpp File Reference
Implementation of functional tests for MySim framework.
#include <cassert>
#include <cmath>
#include <iostream>
#include "funcional_tests.h"
#include "../../src/Flow.h"
#include "../../src/System.h"
#include "../../src/Model.h"
#include "../ComplexFlow.h"
#include "../ExponentialFlow.h"
#include "../LogisticFlow.h"
Functions
int round4 (double value)
Rounds a double value to 4 decimal places.
bool isBetween (double value, double lower, double upper)
Checks if a value is between two bounds (inclusive).
void exponentialFuncionalTest ()
Implementation of exponential functional test.
void logisticalFuncionalTest ()
Implementation of logistic functional test.
void complexFuncionalTest ()
Implementation of complex functional test.
Detailed Description
Implementation of functional tests for MySim framework.
Contains the implementation of functional tests that validate the complete simulation workflows. Each test creates a model with systems and flows, runs the simulation, and verifies the results.
Definition in file funcional_tests.cpp.
Function Documentation
complexFuncionalTest()
void complexFuncionalTest ()
Implementation of complex functional test.
Functional test for complex flow network.
Creates a complex network of 5 systems connected by 6 complex flows. This represents a more realistic system with multiple interconnected components. Simulates 100 time units and verifies all final values.
Implementation of complex functional test.
Validates a complex system with 5 systems (Q1-Q5) connected by 6 complex flows forming a network. Verifies the final state of all systems after 100 simulation steps.
Expected results:
Q1 ≈ 31.8513
Q2 ≈ 18.4003
Q3 ≈ 77.1143
Q4 ≈ 56.1728
Q5 ≈ 16.4612
Definition at line 108 of file funcional_tests.cpp.
                            {
    System q1("Q1", 100.0);
    System q2("Q2", 0.0);
    System q3("Q3", 100.0);
    System q4("Q4", 0.0);
    System q5("Q5", 0.0);
    ComplexFlow f(&q1, &q2);
    ComplexFlow g(&q1, &q3);
    ComplexFlow r(&q2, &q5);
    ComplexFlow t(&q2, &q3);
    ComplexFlow u(&q3, &q4);
    ComplexFlow v(&q4, &q1);
    Model model;
    model.add(&q1);
    model.add(&q2);
    model.add(&q3);
    model.add(&q4);
    model.add(&q5);
    model.add(&f);
    model.add(&g);
    model.add(&r);
    model.add(&t);
    model.add(&u);
    model.add(&v);
    model.run(0, 100);
    assert(round4(q1.getValue()) == round4(31.8513));
    assert(round4(q2.getValue()) == round4(18.4003));
    assert(round4(q3.getValue()) == round4(77.1143));
    assert(round4(q4.getValue()) == round4(56.1728));
    assert(round4(q5.getValue()) == round4(16.4612));
    cout << "complexFuncionalTest OK" << endl;
}
References Model::add(), System::getValue(), round4(), and Model::run().
Referenced by main().
exponentialFuncionalTest()
void exponentialFuncionalTest ()
Implementation of exponential functional test.
Functional test for exponential flow.
Creates a simple model with one system (Population) and one exponential flow from null source to the system. Simulates 10 time units and verifies the result.
Implementation of exponential functional test.
Validates that exponential flow correctly simulates population growth following an exponential curve. Tests with initial population of 10 over 10 time units.
Expected behavior: P(10) = 10 * 1.3^10 ≈ 137.858491849
Definition at line 58 of file funcional_tests.cpp.
                                {
    // P inicial = 10, tempo = 10.
    // Esperado: 10 * 1.3^10 = aproximadamente 137.858491849.
    System pop("Populacao", 10);
    ExponentialFlow nascimento(nullptr, &pop);
    Model model;
    model.add(&pop);
    model.add(&nascimento);
    model.run(0, 10);
    assert(round4(pop.getValue()) == round4(137.858491849));
    cout << "exponentialFuncionalTest OK" << endl;
}
References Model::add(), System::getValue(), round4(), and Model::run().
Referenced by main().
isBetween()
bool isBetween (double value, double lower, double upper)
Checks if a value is between two bounds (inclusive).
Parameters
value The value to check.
lower Lower bound (inclusive).
upper Upper bound (inclusive).
Returns
True if lower <= value <= upper, false otherwise.
Definition at line 47 of file funcional_tests.cpp.
                                                         {
    return value >= lower && value <= upper;
}
Referenced by logisticalFuncionalTest().
logisticalFuncionalTest()
void logisticalFuncionalTest ()
Implementation of logistic functional test.
Functional test for logistic flow.
Creates a model with one system and one logistic flow with population maximum limit. Simulates 100 time units and verifies that population converges to the maximum.
Implementation of logistic functional test.
Validates that logistic flow correctly simulates bounded population growth. Tests with initial population of 10, maximum population of 70, over 100 time units. Population should stabilize at maximum.
Expected behavior: Population converges to approximately 70
Definition at line 83 of file funcional_tests.cpp.
                               {
    // P inicial = 10, Pmax = 70, tempo = 100.
    // Esperado: população próxima de 70.
    System pop("Populacao", 10);
    LogisticFlow nascimento(nullptr, &pop, 70);
    Model model;
    model.add(&pop);
    model.add(&nascimento);
    model.run(0, 100);
    assert(isBetween(pop.getValue(), 69.9, 70.0001));
    cout << "logisticalFuncionalTest OK" << endl;
}
References Model::add(), System::getValue(), isBetween(), and Model::run().
Referenced by main().
round4()
int round4 (double value)
Rounds a double value to 4 decimal places.
Parameters
value The value to round.
Returns
The rounded value.
Definition at line 35 of file funcional_tests.cpp.
                         {
    return int(round(value * 10000.0));
}
Referenced by complexFuncionalTest(), and exponentialFuncionalTest().