main.cpp File Reference
#include "funcional_tests.h"
Macros
#define MAIN_FUNCIONAL_TESTS
Functions
int main ()
Macro Definition Documentation
MAIN_FUNCIONAL_TESTS
#define MAIN_FUNCIONAL_TESTS
Definition at line 2 of file main.cpp.
Function Documentation
main()
int main ()
Definition at line 6 of file main.cpp.
           {
    exponentialFuncionalTest();
    logisticalFuncionalTest();
    complexFuncionalTest();
    return 0;
}
References complexFuncionalTest(), exponentialFuncionalTest(), and logisticalFuncionalTest().